language: objective-c
before_install:
    - brew update
    - brew unlink xctool
    - brew install xctool
install: cd Project; pod install; cd ..
script: xctool -workspace Project/IRFAutoCompletionKit.xcworkspace -scheme Demo test
